# Generated by Django 2.0 on 2022-05-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='averageRating',
            field=models.FloatField(default=0),
        ),
    ]
