# Generated by Django 2.0 on 2022-05-22 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie',
            new_name='book',
        ),
    ]
